---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [1]:
import os
os.getcwd()

'/home/jovyan/work'

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [184]:
import pandas as pd

In [185]:
energy=pd.read_excel('Energy Indicators.xls',skiprows=17,skipfooter=38,na_values = "...")
energy.drop(energy.columns[[0,1]],axis=1,inplace=True)
energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [186]:
energy['Energy Supply']*=1000000
energy['Country'] = energy['Country'].str.replace("[0-9()]+$", "")

In [187]:
energy['Country']=energy['Country'].replace({"Republic of Korea": "South Korea",
'Iran (Islamic Republic of':"Iran",
"Bolivia (Plurinational State of": "Bolivia",
"Falkland Islands (Malvinas": "Falkland Islands",
"Micronesia (Federated States of": "Micronesia",
"Sint Maarten (Dutch part": "Sint Maarten",
"Venezuela (Bolivarian Republic of": "Venezuela",                                            
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"})

In [188]:
energy[energy['Country']=='Iran']

   Country  Energy Supply  Energy Supply per Capita  % Renewable
98    Iran   9.172000e+09                     119.0     5.707721

In [189]:
GDP=pd.read_csv('world_bank.csv',skiprows=4)

GDP['Country Name']=GDP['Country Name'].replace({"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"

})
GDP = GDP.rename(columns={'Country Name': 'Country'})
col_keep=['Country', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
GDP=GDP[col_keep]

In [190]:
GDP.shape

(264, 11)

In [191]:
ScimEn=pd.read_excel('scimagojr-3.xlsx')

In [192]:
ScimEn.shape

(191, 8)

In [193]:
df1=pd.merge(energy,GDP,how='inner',left_on='Country',right_on='Country')

In [194]:
df=pd.merge(df1,ScimEn,how='inner',on='Country')
col_keep=['Country','Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
          'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', 
          '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
df3=df[col_keep]

In [195]:
df4=df3.sort('Rank',ascending=True).reset_index(drop=True)
Top15=df4.head(15)
Top15=Top15.set_index('Country')
Top15.shape

(15, 20)

In [196]:
df6=Top15.copy()

In [197]:
def answer_one():
    return df6
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

 (%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>)

In [198]:
set1=set(energy['Country'])
set2=set(GDP['Country'])
set3=set(ScimEn['Country'])

In [199]:
set1

{'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire, Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'China, Macao Special Administrative Region',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Faeroe Islands',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Réunion',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'State of Palestine',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'The former Yugoslav Republic of Macedonia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Viet Nam',
 'Wallis and Futuna Islands',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [200]:
set4=set1 | set2
unio=set3 | set4
set5=set1 & set2
insec=set3 & set5

In [201]:
unio

{'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Arab World',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire, Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Indian Ocean Territory',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'China, Macao Special Administrative Region',
 'Christmas Island',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 "Côte d'Ivoire",
 'Côte d’Ivoire',
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Ecuador',
 'Egypt',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faeroe Islands',
 'Falkland Islands',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Gambia, The',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Haïti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, Dem. People’s Rep.',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Kyrgyzstan',
 'Lao PDR',
 "Lao People's Democratic Republic",
 'Laos',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao',
 'Macao SAR, China',
 'Macedonia',
 'Macedonia, FYR',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Micronesia, Fed. Sts.',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle income',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North America',
 'North Korea',
 'Northern Mariana Islands',
 'Norway',
 'Not classified',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico',
 'Qatar',
 'Republic of Moldova',
 'Reunion',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Réunion',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Slovakia',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Martin (French part)',
 'St. Vincent and the Grenadines',
 'State of Palestine',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'The former Yugoslav Republic of Macedonia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States',
 'United States Virgin Islands',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Venezuela, RB',
 'Viet Nam',
 'Vietnam',
 'Virgin Islands (U.S.)',
 'Wallis and Futuna Islands',
 'West Bank and Gaza',
 'World',
 'Yemen',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe'}

In [202]:
len(unio)-len(insec)

156

In [203]:
uni=pd.merge(pd.merge(energy,GDP,how='outer',left_on='Country',right_on='Country'),ScimEn,how='outer',left_on='Country',right_on='Country')

In [204]:
uni

,Country,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,Afghanistan,3.210000e+08,10.0,78.669280,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,...,1.973134e+10,1.999032e+10,2.029415e+10,163.0,3.0,3.0,0.0,0.0,0.00,0.0
1,Albania,1.020000e+08,35.0,100.000000,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,...,1.254247e+10,1.279331e+10,1.312082e+10,118.0,23.0,23.0,168.0,14.0,7.30,6.0
2,Algeria,1.959000e+09,51.0,0.551010,1.446474e+11,1.495654e+11,1.531550e+11,1.556055e+11,1.612073e+11,1.658823e+11,...,1.763249e+11,1.830252e+11,1.901632e+11,42.0,1215.0,1197.0,7393.0,1413.0,6.08,40.0
3,American Samoa,NaN,NaN,0.641026,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,180.0,1.0,1.0,0.0,0.0,0.00,0.0
4,Andorra,9.000000e+06,121.0,88.695650,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,...,3.127550e+09,NaN,NaN,168.0,2.0,2.0,13.0,0.0,6.50,1.0
5,Angola,6.420000e+08,27.0,70.909090,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,...,9.626143e+10,1.008863e+11,1.039106e+11,99.0,50.0,50.0,79.0,0.0,1.58,5.0
6,Anguilla,2.000000e+06,136.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,...,1.155982e+09,1.211723e+09,1.256122e+09,169.0,2.0,2.0,0.0,0.0,0.00,0.0
8,Argentina,3.378000e+09,79.0,24.064520,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,...,5.189199e+11,5.212737e+11,NaN,40.0,1223.0,1213.0,10620.0,1654.0,8.68,47.0
9,Armenia,1.430000e+08,48.0,28.236060,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,...,1.073658e+10,1.111236e+10,1.144574e+10,86.0,91.0,91.0,518.0,207.0,5.69,11.0
10,Aruba,1.200000e+07,120.0,14.870690,NaN,NaN,NaN,NaN,2.467704e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,...,1.241484e+12,1.272520e+12,1.301251e+12,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0
12,Austria,1.391000e+09,164.0,72.452820,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,...,4.055298e+11,4.069632e+11,4.104717e+11,35.0,1761.0,1736.0,14580.0,1557.0,8.28,53.0
13,Azerbaijan,5.670000e+08,60.0,6.384345,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,...,5.723834e+10,5.838310e+10,5.902532e+10,67.0,342.0,339.0,548.0,125.0,1.60,11.0
14,Bahamas,4.500000e+07,118.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Bahrain,5.740000e+08,425.0,0.000000,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,...,2.866752e+10,2.995210e+10,3.082866e+10,82.0,111.0,109.0,997.0,33.0,8.98,15.0
16,Bangladesh,1.625000e+09,10.0,1.966329,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,...,1.385969e+11,1.469974e+11,1.566295e+11,63.0,477.0,472.0,1948.0,143.0,4.08,23.0
17,Barbados,1.900000e+07,69.0,0.000000,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,...,4.490036e+09,4.498133e+09,4.542669e+09,140.0,7.0,7.0,14.0,3.0,2.00,3.0
18,Belarus,1.142000e+09,120.0,0.463389,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,...,5.992787e+10,6.096048e+10,5.859052e+10,72.0,240.0,234.0,989.0,119.0,4.12,17.0
19,Belgium,2.338000e+09,210.0,9.959739,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,...,4.930627e+11,4.994502e+11,5.063123e+11,29.0,2697.0,2642.0,23720.0,3300.0,8.79,63.0
20,Belize,1.300000e+07,39.0,64.690030,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,...,1.499280e+09,1.560479e+09,1.590417e+09,185.0,1.0,1.0,6.0,0.0,6.00,1.0
21,Benin,1.700000e+08,16.0,0.000000,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,...,8.026581e+09,8.551638e+09,8.999782e+09,141.0,7.0,7.0,8.0,1.0,1.14,2.0
22,Bermuda,6.000000e+06,88.0,0.000000,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,...,5.151445e+09,NaN,NaN,174.0,2.0,2.0,12.0,0.0,6.00,1.0
23,Bhutan,6.300000e+07,83.0,100.000000,1.076853e+09,1.269887e+09,1.330440e+09,1.419010e+09,1.585473e+09,1.710581e+09,...,1.835844e+09,1.936060e+09,1.999064e+09,136.0,8.0,8.0,36.0,0.0,4.50,2.0
24,Bolivia,3.360000e+08,32.0,31.477120,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,...,2.320795e+10,2.447524e+10,2.544488e+10,113.0,26.0,24.0,103.0,9.0,3.96,5.0
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,...,1.756816e+10,1.775823e+10,1.831896e+10,85.0,92.0,91.0,421.0,48.0,4.58,12.0
27,Botswana,8.600000e+07,39.0,0.131406,1.108667e+10,1.200467e+10,1.275401e+10,1.177803e+10,1.278666e+10,1.356004e+10,...,1.556098e+10,1.605954e+10,1.601864e+10,107.0,34.0,32.0,79.0,5.0,2.32,5.0
28,Brazil,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,...,2.409740e+12,2.412231e+12,2.319423e+12,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0
29,British Virgin Islands,2.000000e+06,85.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,Sint Maarten (Dutch part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,East Asia & Pacific (IDA & IBRD countries),NaN,NaN,NaN,5.438923e+12,6.098467e+12,6.611224e+12,7.110325e+12,7.805156e+12,8.464018e+12,...,9.741747e+12,1.039664e+13,1.106829e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Europe & Central Asia (IDA & IBRD countries),NaN,NaN,NaN,3.212486e+12,3.454927e+12,3.602802e+12,3.420794e+12,3.592526e+12,3.779517e+12,...,3.970061e+12,4.039625e+12,4.037517e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,Latin America & the Caribbean (IDA & IBRD coun...,NaN,NaN,NaN,4.493341e+12,4.756702e+12,4.948056e+12,4.886634e+12,5.178357e+12,5.423951e+12,...,5.751559e+12,5.808023e+12,5.753132e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Middle East & North Africa (IDA & IBRD countries),NaN,NaN,NaN,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,...,1.394728e+12,1.416758e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,South Asia (IDA & IBRD),NaN,NaN,NaN,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,...,2.499225e+12,2.670483e+12,2.862660e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,Sub-Saharan Africa (IDA & IBRD countries),NaN,NaN,NaN,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,...,1.534734e+12,1.605815e+12,1.653644e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,Tanzania,NaN,NaN,NaN,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,...,3.822090e+10,4.088304e+10,4.373172e+10,97.0,56.0,56.0,600.0,69.0,10.71,15.0
296,Upper middle income,NaN,NaN,NaN,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,...,1.786328e+13,1.856972e+13,1.912141e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,St. Vincent and the Grenadines,NaN,NaN,NaN,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,...,6.991892e+08,7.037801e+08,7.139983e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,"Venezuela, RB",NaN,NaN,NaN,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,...,4.391487e+11,4.220465e+11,3.979899e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,Vietnam,NaN,NaN,NaN,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,...,1.366576e+11,1.448347e+11,1.545086e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,West Bank and Gaza,NaN,NaN,NaN,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,...,1.053747e+10,1.042246e+10,1.171414e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,World,NaN,NaN,NaN,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,...,7.104232e+13,7.291072e+13,7.470901e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,"Yemen, Rep.",NaN,NaN,NaN,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,...,2.800914e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,"Congo, Dem. Rep.",NaN,NaN,NaN,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,...,2.550050e+10,2.778776e+10,2.970961e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16.0,6468.0,6441.0,86099.0,14768.0,13.31,102.0
306,Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.0,105.0,104.0,1130.0,75.0,10.76,18.0
307,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,98.0,51.0,51.0,407.0,22.0,7.98,11.0
308,Macao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,104.0,38.0,38.0,208.0,8.0,5.47,6.0
309,North Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,115.0,25.0,25.0,436.0,0.0,17.44,10.0
310,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,127.0,15.0,15.0,4.0,0.0,0.27,1.0
311,Côte d’Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,132.0,10.0,9.0,101.0,4.0,10.10,5.0
312,Netherlands Antilles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,161.0,3.0,3.0,8.0,0.0,2.67,1.0
313,Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,164.0,3.0,3.0,5.0,0.0,1.67,1.0
314,Haïti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,170.0,2.0,2.0,4.0,1.0,2.00,1.0
315,British Indian Ocean Territory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,179.0,1.0,1.0,37.0,0.0,37.00,1.0
316,Christmas Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,188.0,1.0,1.0,0.0,0.0,0.00,0.0
317,Reunion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,189.0,1.0,1.0,2.0,1.0,2.00,1.0

In [205]:
uni.shape

(318, 21)

In [206]:
def answer_two():
    return len(uni)-len(df3)
answer_two()

156

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [129]:
gdp_15=Top15.copy()

In [130]:
gdp_15=gdp_15.iloc[:,-10:]

In [131]:
avg=gdp_15.apply(lambda x:x.mean(),axis=1)
avgGDP=avg.sort_values(ascending=False)

In [132]:
def answer_three():
    return avgGDP
answer_three()

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [133]:
top15=Top15.copy()

In [134]:
top15['avgGDP']=avgGDP
top15.sort('avgGDP', ascending=False,inplace=True)
top15.reset_index(inplace=True)

In [135]:
top15.iloc[5]

Country                     United Kingdom
Rank                                     4
Documents                            20944
Citable documents                    20357
Citations                           206091
Self-citations                       37874
Citations per document                9.84
H index                                139
Energy Supply                     7.92e+09
Energy Supply per Capita               124
% Renewable                        10.6005
2006                           2.41963e+12
2007                            2.4822e+12
2008                           2.47061e+12
2009                           2.36705e+12
2010                            2.4035e+12
2011                           2.45091e+12
2012                           2.47981e+12
2013                           2.53337e+12
2014                           2.60564e+12
2015                           2.66633e+12
avgGDP                         2.48791e+12
Name: 5, dtype: object

In [136]:
def answer_four():
    return top15.iloc[5]['2015']-top15.iloc[5]['2006']
answer_four()

246702696075.3999

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [137]:
def answer_five():
    return top15['Energy Supply per Capita'].mean()
answer_five()

157.59999999999999

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [138]:
sort_renew=Top15.copy()
sort_renew=sort_renew.sort('% Renewable',ascending=False)

In [139]:
sort_renew

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12

In [140]:
six=(sort_renew['% Renewable'].idxmax(), sort_renew['% Renewable'].max())

In [141]:
def answer_six():
    return six
answer_six()

('Brazil', 69.648030000000006)

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [142]:
cit=Top15.copy()
cit['Citratio']=(cit['Self-citations'])/(cit['Citations'])
cit=cit.sort('Citratio', ascending=False)

In [143]:
seven=(cit['Citratio'].idxmax(), cit['Citratio'].max())

In [144]:
type(seven)

tuple

In [145]:
def answer_seven():
    return seven
answer_seven()

('China', 0.68931261793894216)

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [146]:
pop=Top15.copy()
pop['Population']=(pop['Energy Supply'])/(pop['Energy Supply per Capita'])
pop=pop.sort('Population',ascending=False)
pop.head(4)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.75491,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.96908,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.57098,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,3.176154e+08
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.64803,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.059153e+08

In [147]:
eight=pop.index[2]

In [148]:
def answer_eight():
    return eight
answer_eight()

'United States'

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [149]:
cit_per=pop.copy()
cit_per['Citable docs per Capita']=(cit_per['Citable documents'])/(cit_per['Population'])
cit_per.head(3)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,Population,Citable docs per Capita
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.75491,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09,0.000093
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.96908,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09,0.000012
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.57098,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,3.176154e+08,0.000298

In [150]:
nine=cit_per['Citable docs per Capita'].corr(cit_per['Energy Supply per Capita'])

In [151]:
def answer_nine():
    return nine
answer_nine()

0.79400104354429424

In [152]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    hjo=Top15.copy()
    hjo['PopEst'] = hjo['Energy Supply'] / hjo['Energy Supply per Capita']
    hjo['Citable docs per Capita'] = hjo['Citable documents'] / hjo['PopEst']
    hjo.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [153]:
#plot9() # Be sure to comment out plot9() before submitting the assignment!
# from plot 9 it can be observed that energy supply per capita and citable docs per capita are highly correlated.

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [154]:
tenth=Top15.copy()
med=tenth['% Renewable'].median()

In [155]:
tenth['highmed']=tenth['% Renewable']>=med

In [156]:
tenth['HighRenew']=pd.get_dummies(tenth.highmed).iloc[:,1:]

In [157]:
ten=tenth['HighRenew']

In [158]:
def answer_ten():
    return ten
answer_ten()

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: uint8

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [159]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

In [160]:
elven=Top15.copy()
elven['Continent']=pd.Series(ContinentDict)
elven['PopEst'] = elven['Energy Supply'] / elven['Energy Supply per Capita']

In [161]:
elv=elven.groupby('Continent').PopEst

In [162]:
elv.std

In [163]:
[elv.size(),elv.sum(),elv.mean(),elv.std()]

[Continent
 Asia             5
 Australia        1
 Europe           6
 North America    2
 South America    1
 dtype: int64, Continent
 Asia             2.898666e+09
 Australia        2.331602e+07
 Europe           4.579297e+08
 North America    3.528552e+08
 South America    2.059153e+08
 Name: PopEst, dtype: float64, Continent
 Asia             5.797333e+08
 Australia        2.331602e+07
 Europe           7.632161e+07
 North America    1.764276e+08
 South America    2.059153e+08
 Name: PopEst, dtype: float64, Continent
 Asia             6.790979e+08
 Australia                 NaN
 Europe           3.464767e+07
 North America    1.996696e+08
 South America             NaN
 Name: PopEst, dtype: float64]

In [164]:
x=pd.concat([elv.size(),elv.sum(),elv.mean(),elv.std()],axis=1)

In [165]:
x.columns=['size','sum','mean','std']

In [166]:
def answer_eleven():
    return x
answer_eleven()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [167]:
twel=elven.copy()

In [168]:
twel['% Renewable bins']=pd.cut(twel['% Renewable'],5)

In [169]:
twelve=twel.groupby(['Continent','% Renewable bins']).size()

In [170]:
def answer_twelve():
    return twelve
answer_twelve()

Continent      % Renewable bins
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [171]:
thirt=Top15.copy()

In [172]:
abs(1.505540e+13)

15055400000000.0

In [211]:
thirt['PopEst'] = abs(thirt['Energy Supply'] / thirt['Energy Supply per Capita']).map('{:,}'.format)

In [212]:
thirteen=thirt['PopEst'].astype(str)

In [213]:
def answer_thirteen():
    return thirteen
answer_thirteen()

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [176]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    gyu=Top15.copy()
    ax = gyu.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*gyu['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(gyu.index):
        ax.annotate(txt, [gyu['Rank'][i], gyu['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")

In [177]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!

In [178]:
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [179]:
answer_twelve()

Continent      % Renewable bins
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

In [180]:
answer_thirteen()

Country
China                 1,367,645,161.29
United States           317,615,384.62
Japan                   127,409,395.97
United Kingdom           63,870,967.74
Russian Federation      143,500,000.00
Canada                   35,239,864.86
Germany                  80,369,696.97
India                 1,276,730,769.23
France                   63,837,349.40
South Korea              49,805,429.86
Italy                    59,908,256.88
Spain                    46,443,396.23
Iran                     77,075,630.25
Australia                23,316,017.32
Brazil                  205,915,254.24
Name: PopEst, dtype: object

In [207]:
def test_energy(countries):
    """
    Input: a series/ the Country column in Energy
    utf-8 encoded i.e. when reading Energy use
    encoding='utf-8'
    """
    encodedC = '11,7,7,14,7,6,8,19,9,7,5,9,7,10,7,7,10,8,7,7,6,5,7,6,7,32,22,8,6,22,17,8,12,7,10,8,8,6,14,24,4,5,5,9,42,8,7,5,12,10,13,7,4,7,6,14,37,32,7,8,8,18,7,5,11,17,7,7,8,14,16,4,7,6,13,16,5,6,7,7,5,9,6,9,7,10,4,9,8,6,13,6,5,8,7,7,5,9,4,4,7,11,6,5,7,5,6,6,10,5,8,6,10,32,6,7,7,7,5,13,9,10,10,6,8,8,4,5,16,10,10,9,6,10,8,10,10,7,10,7,7,5,5,11,13,11,9,5,7,4,24,6,4,8,5,6,16,8,4,11,6,8,11,5,11,19,7,7,18,6,12,21,11,25,32,5,21,12,7,6,10,12,9,12,8,8,15,7,12,11,5,9,18,5,8,9,6,11,20,10,8,41,11,4,5,19,7,6,12,24,6,6,7,20,14,27,13,28,7,10,7,9,8,25,5,6,8'
    outcome = ['Failed\n', 'Passed\n']
    
    
    
    energy = pd.DataFrame()
    energy['original'] = pd.read_excel('Energy Indicators.xls',
                                   usecols=[1],encoding='utf-8',
                                   index_col=0).loc['Afghanistan':'Zimbabwe'].index.tolist()
    energy['tested'] = countries.str.len()
    energy['actual'] = encodedC.split(',')
    energy['actual'] = energy['actual'].astype(int)
    try:
        energy['Country'] = countries
    except Exception as e:
        print('Failed, error: ',e)
    
    res = 'Test number of records: '
    res += outcome[len(countries)==len(energy)]
    
    res += 'Test the column name: '
    res += outcome [countries.name == 'Country']
    
    res += 'Equality Test: '
    res += outcome[energy['tested'].equals(energy['actual'])]
    
    if not energy['tested'].equals(energy['actual']):
        res += '\nMismatched countries:\n'
        mismatch = energy.loc[energy['tested'] != (energy['actual']), [
            'original', 'Country', 'tested', 'actual']].values.tolist()
        res += '\n'.join('"{:}" miss-cleaned as  "{:}"'.format(o, r)
                         for o, r, s, v in mismatch)
    return res
print(test_energy(energy.loc[:,'Country']))

Test number of records: Passed
Test the column name: Passed
Equality Test: Passed

In [183]:
GDP['Country']

0                                                  Aruba
1                                                Andorra
2                                            Afghanistan
3                                                 Angola
4                                                Albania
5                                             Arab World
6                                   United Arab Emirates
7                                              Argentina
8                                                Armenia
9                                         American Samoa
10                                   Antigua and Barbuda
11                                             Australia
12                                               Austria
13                                            Azerbaijan
14                                               Burundi
15                                               Belgium
16                                                 Benin
17                                          Burkina Faso
18                                            Bangladesh
19                                              Bulgaria
20                                               Bahrain
21                                          Bahamas, The
22                                Bosnia and Herzegovina
23                                               Belarus
24                                                Belize
25                                               Bermuda
26                                               Bolivia
27                                                Brazil
28                                              Barbados
29                                     Brunei Darussalam
                             ...
234    Middle East & North Africa (IDA & IBRD countries)
235                                          Timor-Leste
236                                                Tonga
237                              South Asia (IDA & IBRD)
238            Sub-Saharan Africa (IDA & IBRD countries)
239                                  Trinidad and Tobago
240                                              Tunisia
241                                               Turkey
242                                               Tuvalu
243                                             Tanzania
244                                               Uganda
245                                              Ukraine
246                                  Upper middle income
247                                              Uruguay
248                                        United States
249                                           Uzbekistan
250                       St. Vincent and the Grenadines
251                                        Venezuela, RB
252                               British Virgin Islands
253                                Virgin Islands (U.S.)
254                                              Vietnam
255                                              Vanuatu
256                                   West Bank and Gaza
257                                                World
258                                                Samoa
259                                          Yemen, Rep.
260                                         South Africa
261                                     Congo, Dem. Rep.
262                                               Zambia
263                                             Zimbabwe
Name: Country, dtype: object

In [182]:
def test_gdp(countries):
    """
    Input: a series/ the Country column in GDP
    utf-8 encoded i.e. when reading GDP use
    encoding='utf-8'
    """
    encodedC = '5,7,11,6,7,10,20,9,7,14,19,9,7,10,7,7,5,12,10,8,7,12,22,7,6,7,7,6,8,17,6,8,24,6,30,11,15,5,5,13,8,11,8,7,10,10,22,4,7,14,6,14,7,8,8,7,18,7,43,26,19,45,21,7,16,9,7,5,7,8,14,40,7,4,6,13,21,5,14,7,5,9,6,11,13,17,6,7,9,9,4,6,11,9,8,38,7,5,7,9,16,9,9,9,8,11,5,14,7,4,4,7,6,5,7,6,5,10,5,15,8,8,19,11,6,6,49,7,7,7,5,9,25,44,10,13,9,19,19,7,25,9,10,6,16,24,7,6,7,10,8,26,6,16,13,14,4,5,7,50,10,8,24,10,10,9,6,8,13,7,13,5,7,9,11,6,5,5,11,12,4,18,8,6,4,11,5,16,6,24,11,25,8,8,27,25,16,5,7,18,6,10,12,5,7,9,15,12,11,10,7,6,42,11,18,12,21,8,15,8,6,9,25,10,20,24,4,42,44,4,8,10,12,52,49,11,5,23,41,19,7,6,6,8,6,7,19,7,13,10,30,13,22,21,7,7,18,5,5,11,12,16,6,8'
    outcome = ['Failed\n', 'Passed\n']
    
    
    
    GDP = pd.DataFrame()
    GDP['original'] = pd.read_csv('world_bank.csv',
                                  usecols=[0],encoding='utf-8',
                                  index_col=0).loc['Aruba':'Zimbabwe'].index.tolist()
    GDP['tested'] = countries.str.len()
    GDP['actual'] = encodedC.split(',')
    GDP['actual'] = GDP['actual'].astype(int)
    try:
        GDP['Country'] = countries
    except Exception as e:
        print('Failed, error: ',e)
    
    res = 'Test number of records: '
    res += outcome[len(countries)==len(GDP)]
    
    res += 'Test the column name: '
    res += outcome [countries.name == 'Country']
    
    res += 'Equality Test: '
    res += outcome[GDP['tested'].equals(GDP['actual'])]
    
    if not GDP['tested'].equals(GDP['actual']):
        res += '\nMismatched countries:\n'
        mismatch = GDP.loc[GDP['tested'] != (GDP['actual']), [
            'original', 'Country', 'tested', 'actual']].values.tolist()
        res += '\n'.join('"{:}" miss-cleaned as  "{:}"'.format(o, r)
                         for o, r, s, v in mismatch)
    return res
print(test_gdp(GDP['Country']))

Test number of records: Passed
Test the column name: Passed
Equality Test: Passed